name: Dubber
favicon: null
layout_spectrum: 0.5079902133438736
typography_spectrum: 0.4134544606786221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15274755004793406
  lightness: 0.14205927541479468
  saturation: 0.6138349478133023
  rhythmicContrast: 0.5655492693185806
purpose: []
