name: Dubber
favicon: null
layout_spectrum: 0.33455
typography_spectrum: 0.25228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010002'
    - '#f5f4f2'
    - '#312e27'
    - '#6d6c58'
    - '#c2c0b4'
  brandStrength: 0.125
  lightness: 0.14205927541479468
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
